# Generated by Django 4.2.6 on 2024-06-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
